// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    ConverterGroup: typeof import('./src/components/organisms/ConverterGroup.vue')['default']
    Dropdown: typeof import('./src/components/molecules/Dropdown.vue')['default']
    DropdownButton: typeof import('./src/components/atoms/DropdownButton.vue')['default']
    DropdownOption: typeof import('./src/components/atoms/DropdownOption.vue')['default']
    DropdownOptions: typeof import('./src/components/atoms/DropdownOptions.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GlassPanel: typeof import('./src/components/atoms/GlassPanel.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Listbox: typeof import('@headlessui/vue')['Listbox']
    ListboxButton: typeof import('@headlessui/vue')['ListboxButton']
    ListboxLabel: typeof import('@headlessui/vue')['ListboxLabel']
    ListboxOption: typeof import('@headlessui/vue')['ListboxOption']
    ListboxOptions: typeof import('@headlessui/vue')['ListboxOptions']
    MicrowaveTime: typeof import('./src/components/atoms/MicrowaveTime.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    ScrollShadows: typeof import('./src/components/atoms/ScrollShadows.vue')['default']
    StepPanel: typeof import('./src/components/atoms/StepPanel.vue')['default']
    Switch: typeof import('@headlessui/vue')['Switch']
    SwitchGroup: typeof import('@headlessui/vue')['SwitchGroup']
    SwitchLabel: typeof import('@headlessui/vue')['SwitchLabel']
    Toggle: typeof import('./src/components/atoms/Toggle.vue')['default']
    UilAngleDown: typeof import('virtual:vite-icons/uil/angle-down')['default']
    UilCheck: typeof import('virtual:vite-icons/uil/check')['default']
    UilClockEight: typeof import('virtual:vite-icons/uil/clock-eight')['default']
  }
}

export { }
